Switch from Source Code Pro to Jetbrains Mono
dart-lang/dartdoc pull request #2459
Opened 2020-12-12 23:50 UTC by parlough

This is a feature request as well, so feel free to not be interested in this change, but I previously noticed the current monospace font is a little blurry and many characters feel slightly squished. I gave Jetbrains Mono a go and it looks much better in my opinion and many Dart users use Jetbrains IDEs so it should be nice and familiar to them. It is licensed under the SIL Open Font License 1.1 license.

This also removes Source Sans Pro which was not used at all as far as I could tell.

The rendering result on Chrome Dev (Linux): 

**Previously(Source Code Pro):**
![image](https://user-images.githubusercontent.com/18372958/101999383-12a36a00-3ca2-11eb-8f73-4fbe35cbf06b.png)

**Suggested(Jetbrains Mono):**
![image](https://user-images.githubusercontent.com/18372958/101999379-06b7a800-3ca2-11eb-9ee9-d8b61c40769a.png)

2020-12-13 00:39 UTC, parlough commented
I believe this test is failing due to _fe_analyzer_shared migrating to null safety. I think the following CL should fix it, but I'm not certain:

https://dart-review.googlesource.com/c/sdk/+/175940

2020-12-16 18:56 UTC, jcollins-g requested changes
You're right this looks better.  Could you instead give Roboto Mono a try, as used in code examples on the [dart.dev](https://dart.dev) site, such as at https://dart.dev/samples?  In general when we make changes we try to align to the larger Dart web style where possible.

Also it looks like Travis won't stop trying to run sdk-analyzer against stable unless you resync your PRs, so if you can do that it'll clear the error.

2020-12-16 22:30 UTC, parlough commented
@jcollins-g This looks like an improvement as well, good to go on my end :)

2020-12-16 23:13 UTC, jcollins-g approved these changes
This looks good, code bits are much more readable when I tried this locally.

2021-01-05 16:21 UTC, merged