Minor cleanup to generator utils
dart-lang/dartdoc pull request #2534
Opened 2021-02-24 00:33 UTC by parlough

There's no functional change here, just some small cleanup:

- Use a const version of the JsonEncoder as we don't need a new instance
- Sort before turning into a list and abstract the shared sort functionality into a private method
- Specify the lists as non-growable
- Rename some variables to better indicate what they are

Sorry about the crazy formatting changes, I guess moving the sort method out really changed the `dartfmt` output.

2021-02-24 19:10 UTC, jcollins-g requested changes

2021-02-24 19:10 UTC, jcollins-g commented on lib/src/generator/generator_utils.dart
> +      .toList(growable: false);
Given that `.sorted` already gives us a `List`, the advantage to transforming a local variable to `growable: false` here seems small as the only thing we're doing with it is passing it to the encoder.

2021-02-24 19:10 UTC, jcollins-g commented on lib/src/generator/generator_utils.dart
> +      .toList(growable: false);
same as line 41

2021-02-24 19:10 UTC, jcollins-g commented on lib/src/generator/generator_utils.dart
> +      .map((Categorization cat) {
optional: I'd prefer to just expand all these into full names, e.g. `categorization` or `indexable` or `enclosedElement`, but if that seems unwieldly to you I don't feel strongly on it.

2021-02-24 19:10 UTC, jcollins-g commented on lib/src/generator/generator_utils.dart
> +int _sortElements(Map<String, Object> a, Map<String, Object> b) {
optional:  Maybe _sortElementRepresentations or something would be more clear?

2021-02-24 19:23 UTC, parlough commented on lib/src/generator/dartdoc_generator_backend.dart
> +    if (categories.isEmpty) {
Thanks for the suggestion, definitely a bit nicer this way!

2021-02-25 17:11 UTC, jcollins-g reviewed
Only one little nit left, looks pretty good!

2021-02-25 17:40 UTC, parlough commented
Thanks, should be good to go! :)

2021-02-25 18:17 UTC, jcollins-g approved these changes

2021-02-25 18:18 UTC, merged