Clean up warnings handling
dart-lang/dartdoc pull request #2536
Opened 2021-02-24 03:45 UTC by parlough

Some minor clean up to the warnings handling and limit external value manipulation.

- `packageWarningsByName` is generated using a map literal, which benchmarked slightly faster
- The use of tuples was removed from `PackageWarningCounter.countedWarnings`, instead just using a nested map. This allows easier access to the relations and is a more natural structure for checking for presence of various pairs.
- External access to `countedWarnings` is now an unmodifiable map view so the caller cannot manipulate the map outside of using the public methods.
- External access to `errorCount` and `warningCount` is now limited to a getter.

**Breaking Change:**
- `PackageWarningCounter.countedWarnings` no longer contains tuples as values but rather Maps from the warning kind to their message.
- Users can no longer set `PackageWarningCounter.errorCount` and `PackageWarningCounter.warningCount`, the values can only be retrieved.

2021-02-24 22:42 UTC, jcollins-g requested changes
Some minor stylistic comments, otherwise this looks good.

2021-02-24 22:42 UTC, jcollins-g commented on lib/src/warnings.dart
> +  /// Gets if we've already warned for this [element], [kind], and [message]
suggest `// Returns true if` and ending with period.

2021-02-24 22:51 UTC, parlough commented
Thanks for the feedback, let me know how those modified comments look.

2021-02-25 00:07 UTC, jcollins-g requested changes
This looks pretty good; agreed the double-maps make more sense in retrospect here.  Only minor changes requested.

2021-02-25 00:13 UTC, parlough commented
@jcollins-g What other changes are you looking for? Perhaps you forgot to publish some other comments?

2021-02-25 17:31 UTC, jcollins-g approved these changes
I guess I missed that the comments weren't from an earlier draft, but were already addressed!  Approved.

2021-02-25 17:31 UTC, merged