Very minor comment and space util cleanup
dart-lang/dartdoc pull request #2542
Opened 2021-02-24 15:53 UTC by parlough

- Adds some extra early failure checks
- Don't use string interpolation when not necessary
- Switch to using built in `StringBuffer.writeln` instead of manually appending `\n`

2021-02-24 17:33 UTC, parlough commented
The macOS test has been intermittently failing due to timeouts, if you resubmit the checks it _may_ be fine.

2021-02-25 00:46 UTC, jcollins-g requested changes
tiny cosmetic bit

2021-02-25 00:46 UTC, jcollins-g commented on lib/src/utils.dart
> +  // TODO Once we migrate to null safety, prohibit null here
format for TODOs is "TODO:" in our code base (or TODO(username):)

2021-02-25 00:46 UTC, jcollins-g commented on lib/src/utils.dart
> +      yield line.substring(minimumSeen);
Yes, this makes more sense :-D

2021-02-25 17:51 UTC, jcollins-g approved these changes

2021-02-25 17:51 UTC, merged