Warn if the user did not specify a language on the fenced code block
dart-lang/dartdoc pull request #2559
Opened 2021-03-07 22:03 UTC by parlough

Warn users when they don't specify a language after the ``` or ~~~ in a fenced code block.

2021-03-08 18:03 UTC, jcollins-g requested changes

2021-03-08 23:37 UTC, parlough commented on lib/src/warnings.dart
> +  missingCodeBlockLanguage,
Thanks for pointing that out, should be good now, but I'm not so great at wording. If you had any suggestions around the warning descriptions, they would be welcome! 

Outside of the scope of this PR but perhaps we could use a switch to lazily build the map so the analyzer could catch a missing enum usage there.

2021-03-08 23:54 UTC, parlough commented
As a note, I will follow up on the SDK repo with fixes for the few warnings this currently produces there.

2021-03-09 17:10 UTC, jcollins-g approved these changes
Approved; we'll disable this warning if it turns out to be too much.

Out of curiosity, have you used the compare-flutter-warnings grinder to get a sense for how many new warnings this introduces?

2021-03-09 17:11 UTC, merged