Adopt badge design for all features #3047
dart-lang/dartdoc pull request #3101
Opened 2022-07-28 19:41 UTC by klr981

## Description:
- style.css : the "features" styling now contains the same style as the "feature" styling (The styling for the badge for Null Safety).  
- model_element_renderer.dart : The line changed now iterates each feature and makes it a HTML element type span containing the name of the feature for the element class and the text inside of the element.
- _features.html : To avoid the div in the template to adopt the styling of features the name was changed from "features" to "features-div".

2022-07-28 20:13 UTC, parlough commented
This standardization will be nice! Could you add a before and after screenshot to the PR as a reference?

Also, you can add something "Closes https://github.com/dart-lang/dartdoc/issues/3047" or "Fixes https://github.com/dart-lang/dartdoc/issues/3047" to the PR description so it automatically links the PR and issue and will close it on merge.

2022-07-28 21:11 UTC, klr981 commented
### Screenshots for reference:

- Before the changes
![Before](https://user-images.githubusercontent.com/106621169/181637638-04aab78f-c00b-462a-833a-0c3e3fa93483.png)

- After the changes
![After](https://user-images.githubusercontent.com/106621169/181637631-d33afe0e-a50d-4a5b-ba35-6359985d4c1d.png)

Also, I added the fix issue tag to the PR description, thank you for the tip!


> This standardization will be nice! Could you add a before and after screenshot to the PR as a reference?
> 
> Also, as a small note, you can add something "Closes #3047" or "Fixes #3047" to the PR description so it automatically [links the PR and issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) and then will close the issue automatically when merged.

2022-07-29 18:01 UTC, devoncarew commented
It looks like the text for annotations has changed? Here's the before and after for the annotations on main(), above:

<img width="194" alt="Screen Shot 2022-07-29 at 10 57 11 AM" src="https://user-images.githubusercontent.com/1269969/181817658-72792ef4-ba29-49ec-89ce-c8c2b8a039a4.png">

<img width="319" alt="Screen Shot 2022-07-29 at 10 56 58 AM" src="https://user-images.githubusercontent.com/1269969/181817686-84655945-0531-4bd1-a29d-95d9f880ddd4.png">

And from those screenshots, it's not clear that we do want to use badge decorations for user annotations / all annotations? You may want to include some other screenshots (of a deprecated annotation, or other typical annotations) to better see what they would look like.

2022-07-29 18:11 UTC, keertip commented
We want to adopt the badge for features and not all user annotations. @klr981

2022-07-31 02:48 UTC, srawlins requested changes

2022-07-31 02:48 UTC, srawlins commented on lib/resources/styles.css
> +/* The badge under a declaration for things like "const", "read-only", etc. and for the badges inline like Null safety*/
I think it would be beneficial to link to the items in the backend code, I think in feature.dart?

2022-08-02 20:43 UTC, klr981 commented
![Screenshot 2022-08-02 1 34 45 PM](https://user-images.githubusercontent.com/106621169/182469344-cb5cff07-796a-4885-8922-a2ed56248c91.png)

New changes now only changes the feature styling and not annotations.

2022-08-02 23:21 UTC, srawlins commented on lib/resources/styles.css
> +/* The badge under a declaration for things like "const", "read-only", etc. and for the badges inline like Null safety*/
Looks good.

2022-08-02 23:22 UTC, srawlins requested changes
I suspect you will need to rebase from master and re-run `dart run build_runner build`.

2022-08-02 23:22 UTC, srawlins commented on lib/src/model/feature.dart
> +  String  cssClassName() => 'feature';
Looks like this file is not formatted?

2022-08-02 23:22 UTC, srawlins commented on lib/src/model/feature.dart
> +  String  cssClassName() => 'feature';
This should be a getter like `String get cssClassName`

2022-08-03 05:07 UTC, srawlins approved these changes

2022-08-03 05:07 UTC, srawlins commented on lib/src/model/annotation.dart
> +  String get cssClassName => 'annotation';
If we have no CSS rules associated with this class name, it would be better to just leave it blank.

2022-08-04 19:27 UTC, srawlins approved these changes
Looks great!

2022-08-04 19:27 UTC, merged